sudo: false
bundler_args: "--standalone --binstubs --without development"
cache: bundler
script: script/test_all
services:
  - mongodb
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database will_paginate;'
  - psql -c 'create database will_paginate;' -U postgres
rvm:
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - 3.0.0
gemfile:
  - Gemfile
  - Gemfile.rails5.2
  - Gemfile.rails6.0
  - Gemfile.rails6.1
  - Gemfile.rails-edge
